### ISSUE TITLE
Filtreleme hatası

### ISSUE THREAD

**Issue by alperalin** [patika-167-react-bootcamp/hw-week-2-dev-emr#2]
İki şık işaretliyken gönderen kişinin yaptığı işlemler listelenmezken gönderilen kişinin listeleniyor.

<img width="881" alt="Screen Shot 2022-02-18 at 16 19 44" src="https://user-images.githubusercontent.com/5332145/154690589-4d90c626-6f42-4641-8e26-bcddcff14d7b.png">
<img width="874" alt="Screen Shot 2022-02-18 at 16 19 56" src="https://user-images.githubusercontent.com/5332145/154690606-ee50d3ba-462e-48a4-9bda-ebb005d28cea.png">

**Comment by etemel** [comment]
yeterince test etmemişim teşekkürler uyarı için 😅
kodu güncelledim :)
